# Generated by Django 5.1.4 on 2025-01-09 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_producto_imagen_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria'),
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('nombre', 'categoria')},
        ),
    ]
